name: HyterMMO
version: '${version}'
author: PinkJelly/Kasumiko
main: org.example.hyterMMO.hyterMMO
api-version: '1.21'
depend: [WorldEdit, WorldGuard]

commands:
  HMO:
    description: principal command
    aliases:
      - HyterMMO
  Zones:
    description: "Manage regions"
    usage: "/hmmo z <create|delete|flag|list>"
    aliases: [ z, zones, zone ,zo ]
    permission-message: "You do not have permission to use this command."

permissions:
  hyterMMO.admin.zcreate:
    description: "Allows creating regions."
    default: op