name: HyterMMO
version: '${version}'
author: PinkJelly/Kasumiko
main: org.jellypink.hyterMMO.Main
api-version: '1.21'
depend: [WorldEdit, WorldGuard]

commands:
  hmmo:
    description: Principal command.
    usage: "/hmmo <command>"
    aliases: [ hmmocore, hmmo ]

permissions:
  hyterMMO.admin.zcreate:
    description: "Allows creating regions."
    default: op